#!/bin/bash
# Setup web-ui .env.local from deployment outputs
set -e

echo "🚀 Web UI 環境をセットアップしています..."

# Get deployment ID
DEPLOYMENT_ID=$(node -p "require('./deployment-config.json').deploymentId" 2>/dev/null || echo "default")
STACK_NAME="AgentStack-${DEPLOYMENT_ID}"

# Parse flags
FORCE=false
MOCK_MODE=""
for arg in "$@"; do
    case $arg in
        --force) FORCE=true ;;
        --mock) MOCK_MODE="true" ;;
        --no-mock) MOCK_MODE="false" ;;
    esac
done

# Check if .env.local exists
if [[ -f "web-ui/.env.local" && "$FORCE" == "false" ]]; then
    echo "⚠️  web-ui/.env.local は既に存在します"
    echo "   再生成するには --force を付けて実行してください"
    exit 0
fi

# Get CDK outputs from CloudFormation
echo "📊 ${STACK_NAME} を照会しています..."
CDK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region us-east-1 --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "❌ ${STACK_NAME} を照会できませんでした。先にエージェントスタックをデプロイしてください。"
    exit 1
}

# Parse CDK outputs
RUNTIME_ARN=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeArn") | .OutputValue // empty')
RUNTIME_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeId") | .OutputValue // empty')
MEMORY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MemoryId") | .OutputValue // empty')
GATEWAY_URL=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayUrl") | .OutputValue // empty')
GATEWAY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayId") | .OutputValue // empty')

# Get Visa Lambda proxy URL from VisaLambdaStack
VISA_STACK_NAME="VisaLambdaStack-${DEPLOYMENT_ID}"
echo "📊 ${VISA_STACK_NAME} を照会しています..."
VISA_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$VISA_STACK_NAME" --region us-east-1 --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "⚠️  ${VISA_STACK_NAME} を照会できませんでした。Visa Lambda がデプロイされていません - モックモードを使用します。"
    VISA_PROXY_URL=""
}
if [[ -n "$VISA_OUTPUTS" && "$VISA_OUTPUTS" != "null" ]]; then
    VISA_PROXY_URL=$(echo "$VISA_OUTPUTS" | jq -r '.[] | select(.OutputKey=="VisaProxyApiUrl") | .OutputValue // empty')
    # Remove trailing slash if present
    VISA_PROXY_URL=${VISA_PROXY_URL%/}
fi

# Get Visa credentials from Secrets Manager
echo "📊 Secrets Manager から Visa 認証情報を取得しています..."
VISA_API_KEY=$(aws secretsmanager get-secret-value --secret-id "visa/api-key" --query SecretString --output text 2>/dev/null) || VISA_API_KEY=""

# Get Google Maps API key from SSM Parameter Store
echo "📊 SSM から Google Maps API キーを取得しています..."
GOOGLE_MAPS_API_KEY=$(aws ssm get-parameter --name "/concierge-agent/travel/google-maps-key" --query "Parameter.Value" --with-decryption --output text 2>/dev/null) || GOOGLE_MAPS_API_KEY=""

# Read Amplify outputs
if [[ ! -f "amplify_outputs.json" ]]; then
    echo "❌ amplify_outputs.json が見つかりません。先に Amplify をデプロイしてください。"
    exit 1
fi

REGION=$(jq -r '.custom.region // "us-east-1"' amplify_outputs.json)
USER_POOL_ID=$(jq -r '.auth.user_pool_id // empty' amplify_outputs.json)
USER_POOL_CLIENT_ID=$(jq -r '.auth.user_pool_client_id // empty' amplify_outputs.json)

# Validate required values
if [[ -z "$RUNTIME_ARN" || -z "$USER_POOL_ID" || -z "$USER_POOL_CLIENT_ID" ]]; then
    echo "❌ 必須の値が不足しています。両方のスタックがデプロイされていることを確認してください。"
    exit 1
fi

# Determine mock mode: --mock flag overrides, otherwise default to false (real API)
if [[ "$MOCK_MODE" == "true" ]]; then
    FINAL_MOCK_MODE="true"
else
    FINAL_MOCK_MODE="false"
fi

# Generate .env.local
cat > web-ui/.env.local << EOF
# Auto-generated by setup-web-ui-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Cognito Configuration
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}

# Agent Runtime Configuration
VITE_AGENT_RUNTIME_ARN=${RUNTIME_ARN}
VITE_AGENT_RUNTIME_ID=${RUNTIME_ID}
VITE_AGENT_ENDPOINT_NAME=DEFAULT

# Memory Configuration
VITE_MEMORY_ID=${MEMORY_ID}

# Gateway Configuration
VITE_GATEWAY_URL=${GATEWAY_URL}
VITE_GATEWAY_ID=${GATEWAY_ID}

# Visa Integration (default: no-mock when proxy available, use --mock to override)
VITE_VISA_MOCK_MODE=${FINAL_MOCK_MODE}
VISA_INTEGRATION_ENABLED=true
VITE_VISA_API_KEY=${VISA_API_KEY}
VITE_VISA_CLIENT_APP_ID=VICTestAccountTR
VITE_VISA_IFRAME_URL=https://sbx.vts.auth.visa.com
VITE_VISA_PROXY_URL=${VISA_PROXY_URL}

# Google Maps API Key
VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
EOF

echo "✅ web-ui/.env.local を作成しました"

if [[ -n "$VISA_PROXY_URL" ]]; then
    echo "✅ Visa プロキシ URL を設定しました: $VISA_PROXY_URL"
    echo "   VITE_VISA_MOCK_MODE=false"
else
    echo "⚠️  Visa Lambda がデプロイされていません - モックモードを使用します"
fi

if [[ -n "$VISA_API_KEY" ]]; then
    echo "✅ Secrets Manager から Visa API キーを読み込みました"
else
    echo "⚠️  Secrets Manager に Visa API キーが見つかりません (visa/api-key)"
fi

if [[ -n "$GOOGLE_MAPS_API_KEY" ]]; then
    echo "✅ SSM から Google Maps API キーを読み込みました"
else
    echo "⚠️  SSM に Google Maps API キーが見つかりません (/concierge-agent/travel/google-maps-key)"
fi

echo ""
echo "次のステップ: cd web-ui && npm run dev"
